# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdGTXqkR1Ln95P7b_3tHzEgPWcRkE8nY
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("housing.csv")

df["total_bedrooms"] = df["total_bedrooms"].fillna(
    df["total_bedrooms"].median()
)

df = pd.get_dummies(
    df,
    columns=["ocean_proximity"],
    drop_first=True,
    dtype=float
)

X = df.drop("median_house_value", axis=1).astype(float).values
y = df["median_house_value"].values

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

class LinearRegressionGD:

    def __init__(self, lr=0.01, epochs=2000):
        self.lr = lr
        self.epochs = epochs

    def fit(self, X, y):

        m, n = X.shape

        self.w = np.zeros(n)
        self.b = 0

        self.losses = []

        for _ in range(self.epochs):

            y_pred = np.dot(X, self.w) + self.b

            dw = (1/m) * np.dot(X.T, (y_pred - y))
            db = (1/m) * np.sum(y_pred - y)

            self.w -= self.lr * dw
            self.b -= self.lr * db

            loss = np.mean((y_pred - y) ** 2)
            self.losses.append(loss)

    def predict(self, X):
        return np.dot(X, self.w) + self.b

model = LinearRegressionGD()

model.fit(X_train, y_train)

pred = model.predict(X_test)

import matplotlib.pyplot as plt

from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

print("Custom MSE:", mean_squared_error(y_test, pred))
print("Custom R2:", r2_score(y_test, pred))

plt.plot(model.losses)
plt.xlabel("Iterations")
plt.ylabel("Loss")
plt.title("Loss Curve")
plt.show()

sk_model = LinearRegression()

sk_model.fit(X_train, y_train)

sk_pred = sk_model.predict(X_test)

print("Sklearn MSE:", mean_squared_error(y_test, sk_pred))
print("Sklearn R2:", r2_score(y_test, sk_pred))