# -*- coding: utf-8 -*-
"""polynomial_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Y9B5PJ8paIyXeqGlLtdUEhQMuRy8LuN
"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import PolynomialFeatures

df = pd.read_csv("housing.csv")

X = df[["median_income"]].values
y = df["median_house_value"].values

poly1 = PolynomialFeatures(degree=1)
poly2 = PolynomialFeatures(degree=2)
poly5 = PolynomialFeatures(degree=5)

X1 = poly1.fit_transform(X)
X2 = poly2.fit_transform(X)
X5 = poly5.fit_transform(X)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

m1 = LinearRegression()
m2 = LinearRegression()
m5 = LinearRegression()

m1.fit(X1, y)
m2.fit(X2, y)
m5.fit(X5, y)

print("Degree 1 R2:", r2_score(y, m1.predict(X1)))
print("Degree 2 R2:", r2_score(y, m2.predict(X2)))
print("Degree 5 R2:", r2_score(y, m5.predict(X5)))

import matplotlib.pyplot as plt

x_grid = np.linspace(
    X.min(),
    X.max(),
    500
).reshape(-1,1)

plt.figure(figsize=(8,5))

plt.scatter(X, y, s=5)

plt.plot(
    x_grid,
    m1.predict(poly1.transform(x_grid)),
    label="Degree 1"
)

plt.plot(
    x_grid,
    m2.predict(poly2.transform(x_grid)),
    label="Degree 2"
)

plt.plot(
    x_grid,
    m5.predict(poly5.transform(x_grid)),
    label="Degree 5"
)

plt.legend()
plt.title("Polynomial Regression")
plt.show()

print("""
Degree 5 overfits because the curve becomes
too complex and starts fitting noise rather
than the true relationship in the data.
""")