# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuylZvhpDNZCOUuiYaaxDOm83UcBZC9Z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression


df = pd.read_csv("housing.csv")

df['total_bedrooms'] = df['total_bedrooms'].fillna(
    df['total_bedrooms'].median()
)

X = df[['median_income']].values

y = df['median_house_value'].values.reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

mean = X_train.mean()
std = X_train.std()

X_train = (X_train - mean) / std
X_test = (X_test - mean) / std

w = 0
b = 0

learning_rate = 0.01
epochs = 1000

m = len(X_train)

losses = []

for epoch in range(epochs):

    y_pred = w * X_train + b

    loss = np.mean(
        (y_pred - y_train) ** 2
    )

    losses.append(loss)

    dw = (
        2 / m
    ) * np.sum(
        (y_pred - y_train) * X_train
    )

    db = (
        2 / m
    ) * np.sum(
        y_pred - y_train
    )

    w = w - learning_rate * dw
    b = b - learning_rate * db

y_test_pred = w * X_test + b

print("Scratch Linear Regression")

print(
    "MSE =",
    mean_squared_error(
        y_test,
        y_test_pred
    )
)

print(
    "R2 =",
    r2_score(
        y_test,
        y_test_pred
    )
)

model = LinearRegression()

model.fit(
    X_train,
    y_train
)

sk_pred = model.predict(
    X_test
)

print("\nSklearn Linear Regression")

print(
    "MSE =",
    mean_squared_error(
        y_test,
        sk_pred
    )
)

print(
    "R2 =",
    r2_score(
        y_test,
        sk_pred
    )
)

plt.plot(losses)

plt.xlabel("Iterations")
plt.ylabel("Loss")
plt.title("Loss Curve")

plt.show()