# -*- coding: utf-8 -*-
"""polynomial_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPNfN-R0WbPZLgvGEhMcFXAdzD8EdXda
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score


df = pd.read_csv("housing.csv")

df['total_bedrooms'] = df['total_bedrooms'].fillna(
    df['total_bedrooms'].median()
)

X = df[['median_income']]

y = df['median_house_value']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

degrees = [1, 2, 5]

plt.figure(figsize = (10, 6))

for degree in degrees:

    poly = PolynomialFeatures(
        degree = degree
    )

    X_train_poly = poly.fit_transform(
        X_train
    )

    X_test_poly = poly.transform(
        X_test
    )

    model = LinearRegression()

    model.fit(
        X_train_poly,
        y_train
    )

    pred = model.predict(
        X_test_poly
    )

    print(
        "Degree",
        degree,
        "R2 =",
        r2_score(
            y_test,
            pred
        )
    )

    order = np.argsort(
        X_test.values.flatten()
    )

    plt.plot(
        X_test.values.flatten()[order],
        pred[order],
        label = f"Degree {degree}"
    )

plt.scatter(
    X_test,
    y_test,
    s = 5
)

plt.xlabel("Median Income")
plt.ylabel("Median House Value")

plt.legend()

plt.show()

"""# Degree 5 is most likely to overfit.

# The curve becomes very flexible and starts
# following noise instead of the true trend.

# If training performance improves but
# test R2 stops improving or decreases,
# overfitting is occurring.
"""